# Wine

### Introduction:

This exercise is a adaptation from the UCI Wine dataset.
The only pupose is to practice deleting data with pandas.

### Step 1. Import the necessary libraries

In [54]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data).

### Step 3. Assign it to a variable called wine

In [28]:
wine = pd.read_csv('E:/ai/project/wine.data')
wine

,1,14.23,1.71,2.43,15.6,127,2.8,3.06,.28,2.29,5.64,1.04,3.92,1065
0,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
1,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
2,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
3,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
4,1,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
173,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
174,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
175,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
176,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

### Step 4. Delete the first, fourth, seventh, nineth, eleventh, thirteenth and fourteenth columns

In [29]:
wine.drop(columns=['1','2.43','2.8','.28','5.64','3.92','1065'], inplace=True , axis=1)

### Step 5. Assign the columns as below:

The attributes are (donated by Riccardo Leardi, riclea '@' anchem.unige.it):  
1) alcohol  
2) malic_acid  
3) alcalinity_of_ash  
4) magnesium  
5) flavanoids  
6) proanthocyanins  
7) hue

In [30]:
wine.rename(columns={'14.23':'alcohol',
                    '1.71':'malic_acid',
                    '15.6':'alcalinity_of_ash',
                    '127':'magnesium',
                    '3.06':'flavanoids',
                     '2.29':'proanthocyanins',
                     '1.04':'proanthocyanins',} , inplace=True)
wine

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,proanthocyanins
0,13.20,1.78,11.2,100,2.76,1.28,1.05
1,13.16,2.36,18.6,101,3.24,2.81,1.03
2,14.37,1.95,16.8,113,3.49,2.18,0.86
3,13.24,2.59,21.0,118,2.69,1.82,1.04
4,14.20,1.76,15.2,112,3.39,1.97,1.05
...,...,...,...,...,...,...,...
172,13.71,5.65,20.5,95,0.61,1.06,0.64
173,13.40,3.91,23.0,102,0.75,1.41,0.70
174,13.27,4.28,20.0,120,0.69,1.35,0.59
175,13.17,2.59,20.0,120,0.68,1.46,0.60
176,14.13,4.10,24.5,96,0.76,1.35,0.61

### Step 6. Set the values of the first 3 rows from alcohol as NaN

In [55]:
wine.loc[0:2,'alcohol']=np.NAN

### Step 7. Now set the value of the rows 3 and 4 of magnesium as NaN

In [56]:
wine.loc[2:3,'magnesium']=np.NAN

### Step 8. Fill the value of NaN with the number 10 in alcohol and 100 in magnesium

In [63]:
wine.alcohol = wine.alcohol.fillna(10)
wine.magnesium = wine.magnesium.fillna(100)
wine.head(30)

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,proanthocyanins
0,10.00,1.78,11.2,100,2.76,1.28,1.05
1,10.00,2.36,18.6,101,3.24,2.81,1.03
2,10.00,1.95,16.8,100,3.49,2.18,0.86
3,13.24,2.59,21.0,100,2.69,1.82,1.04
4,14.20,1.76,15.2,112,3.39,1.97,1.05
5,14.39,1.87,14.6,96,2.52,1.98,1.02
6,14.06,2.15,17.6,121,2.51,1.25,1.06
7,14.83,1.64,14.0,97,2.98,1.98,1.08
8,13.86,1.35,16.0,98,3.15,1.85,1.01
9,14.10,2.16,18.0,105,3.32,2.38,1.25
10,14.12,1.48,16.8,95,2.43,1.57,1.17
11,13.75,1.73,16.0,89,2.76,1.81,1.15
12,14.75,1.73,11.4,91,3.69,2.81,1.25
13,14.38,1.87,12.0,102,3.64,2.96,1.20
14,13.63,1.81,17.2,112,2.91,1.46,1.28
15,14.30,1.92,20.0,120,3.14,1.97,1.07
16,13.83,1.57,20.0,115,3.40,1.72,1.13
17,14.19,1.59,16.5,108,3.93,1.86,1.23
18,13.64,3.10,15.2,116,3.03,1.66,0.96
19,14.06,1.63,16.0,126,3.17,2.10,1.09
20,12.93,3.80,18.6,102,2.41,1.98,1.03
21,13.71,1.86,16.6,101,2.88,1.69,1.11
22,12.85,1.60,17.8,95,2.37,1.46,1.09
23,13.50,1.81,20.0,96,2.61,1.66,1.12
24,13.05,2.05,25.0,124,2.68,1.92,1.13
25,13.39,1.77,16.1,93,2.94,1.45,0.92
26,13.30,1.72,17.0,94,2.19,1.35,1.02
27,13.87,1.90,19.4,107,2.97,1.76,1.25
28,14.02,1.68,16.0,96,2.33,1.98,1.04
29,13.73,1.50,22.5,101,3.25,2.38,1.19

### Step 9. Count the number of missing values

In [60]:
wine.isnull().count()

alcohol              177
malic_acid           177
alcalinity_of_ash    177
magnesium            177
flavanoids           177
proanthocyanins      177
proanthocyanins      177
dtype: int64

### Step 10.  Create an array of 10 random numbers up until 10

In [61]:
rand = np.random.randint(0,11,10)

### Step 11.  Use random numbers you generated as an index and assign NaN value to each of cell.

### Step 12.  How many missing values do we have?

### Step 13. Delete the rows that contain missing values

### Step 14. Print only the non-null values in alcohol

### Step 15.  Reset the index, so it starts with 0 again

### BONUS: Create your own question and answer it.